version: '3.9'
services:
  get-user:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "grabber"
    restart: always
    env_file:
      - .env
    volumes:
      - /var/log/grabber:/app/log:rw